#=====================================
#
# NKD - A simple Jekyll boilerplate
#
# More on Jekyll: http://jekyllrb.com/
#
#=====================================

# This will be the first part of the title tag for your site 
# <title> {{site.name}} </title>
# ============================================================
name: "Twnsnd Co. "

# Populates the meta description for the site. Should be under 150 characters for best SEO results.
# ============================================================
description: "Insouciant describes me well."

# Owner (organization or individual) of site content - You'll want to change this from mrmrs :)
# ============================================================
author: "Twnsnd Co"

# Change this to your production URL
# ============================================================
url: "http://twnsnd.co"

# Publish future posts or not option. 
# ============================================================
future: true

# "A list of directories (including trailing slash) and files to exclude from the conversion"
# I normally exclude _sass, README*, and .gitignore
# Directories that start with an underscore _ are not copied over by default. Still like to include _sass anyways.
# ============================================================
exclude: [README.md, Rakefile, .gitignore, _sass, templates]

# Pagination variable for how many posts to show in a list
# ============================================================
paginate: 6

timezone:    America/New_York
future:      true
pygments:    true
markdown:    kramdown

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false

  coderay:
    coderay_line_numbers: 
    coderay_line_numbers_start: 1
    coderay_tab_width: 4
    coderay_bold_every: 10
    coderay_css: class


# Links to include in top navigation
# For external links add external: true
# ============================================================
links:
  - title: Work
    url: /work
  - title: Donate
    url: http://gtat.me/balzac/donate
    external: true
  - title: Github
    url: https://github.com/ColeTownsend/Balzac-for-Jekyll
    external: true

# Style of permalinks
# ============================================================
permalink: /:categories/:title

# Variable format options for URL styles below
# ============================================================
# pretty                                          => /2009/04/29/slap-chop/index.html
# /:month-:day-:year/:title.html/                 => 04-29-2009/slap-chop.html
# /blog/:year/:month/:day/:title                  => /blog/2009/04/29/slap-chop/index.html

# Uncomment if you have pygments installed. Used for code syntax highlighting. 
# If you're not doing syntax highlighting you can delete this.
pygments: true