name: "Twnsnd Co."
description: "I'm just happy to be here."
author: "Twnsnd Co"
url: "http://twnsnd.co"
email: cole@twnsnd.co
twitter: twnsndco
version: 63

future: true

# images
images_url: /images/inline/
image:
  source: images/inline
# dribbble
dribbble_set:
  user:            'coletownsend'
  shots_per_page:  9
  page:            1
  gallery_tag:     'ul'
  gallery_class:   'dribbble-grid'
  is_list:         true
  a_target:        '_blank'
  full_size:       false

# glynn
ftp_host: 'ftp.coletownsend.com'
ftp_dir: '../beta-site'
ftp_passive: false


# A list of directories (including trailing slash) and files to exclude from the conversion
# ============================================================
exclude: ['README.md', 'Procfile', 'Rakefile', '*.codekit', 'Gemfile.lock', 'Gemfile', '.gitignore', 'templates', '*.sublime-workspace', '*.sublime-project', '_config.yml', '*.scssc', 'bower_components']
include:  ['.htaccess']

timezone:    America/New_York
future:      true
highlighter: pygments
markdown: rdiscount
rdiscount:
  extensions:
    - smart
    - generate_toc
    - footnotes


# Links to include in top navigation
# For external links add external: true
# ============================================================
links:
  - title: Home
    url: /
  - title: Work
    url: /work/
  - title: Journal
    url: /journal/
  - title: About
    url: /about/

permalink: /:categories/:title

paginate: 1000

sitemap:
    file: "/sitemap.xml"
    exclude:
        - "/atom.xml"
        - "/feed.xml"
        - "/feed/index.xml"
    include_posts:
        - "/index.html"
    change_frequency_name: "change_frequency"
    priority_name: "priority"
