name: "Twnsnd Co."
description: "Insouciant describes me well."
author: "Twnsnd Co"
url: "http://beta.twnsnd.co"
email: cole@twnsnd.co
twitter: twnsndco
version: 2

future: true

# images
images_url: /images/inline/
image:
  source: images/inline


ftp_host: 'ftp.coletownsend.com'
ftp_dir: '/beta-site'
ftp_passive: true

# optional
ftp_port: 21                  # default 21
ftp_username: 'glynn@coletownsend.com'     # default read from stdin
ftp_password: 'jekyll%%glynn93' # default read from stdin

# A list of directories (including trailing slash) and files to exclude from the conversion
# ============================================================
exclude: ['README.md', 'Rakefile', '.gitignore', 'templates', '.sublime-workspace', '.sublime-project', '_config.yml']
include:  ['.htaccess']

timezone:    America/New_York
future:      true
highlighter:    true
markdown: rdiscount
rdiscount:
  extensions:
    - smart
    - generate_toc
    - footnotes


# Links to include in top navigation
# For external links add external: true
# ============================================================
links:
  - title: Home
    url: /
  - title: Work
    url: /work/
  - title: Journal
    url: /journal/
  - title: About
    url: /about/

permalink: /:categories/:title

paginate: 6

sitemap:
    file: "/sitemap.xml"
    exclude:
        - "/atom.xml"
        - "/feed.xml"
        - "/feed/index.xml"
    include_posts:
        - "/index.html"
    change_frequency_name: "change_frequency"
    priority_name: "priority"
