name: "Twnsnd Co."
description: "Insouciant describes me well."
author: "Twnsnd Co"
url: "http://beta.twnsnd.co"
email: cole@twnsnd.co
twitter: twnsndco
version: 1

future: true

images_url: /images/inline/
image:
  source: images/inline

# A list of directories (including trailing slash) and files to exclude from the conversion
# ============================================================
exclude: ['README.md', 'Rakefile', '.gitignore', '_sass', 'templates', '.sublime-workspace', '.sublime-project']
include:  ['.htaccess']

timezone:    America/New_York
future:      true
pygments:    true
markdown: rdiscount
rdiscount:
  extensions:
    - smart
    - generate_toc


# Links to include in top navigation
# For external links add external: true
# ============================================================
links:
  - title: Home
    url: /
  - title: Work
    url: /work/
  - title: Journal
    url: /journal/
  - title: About
    url: /about/

permalink: /:categories/:title

paginate: 4

sitemap:
    file: "/sitemap.xml"
    exclude:
        - "/atom.xml"
        - "/feed.xml"
        - "/feed/index.xml"
    include_posts:
        - "/index.html"
    change_frequency_name: "change_frequency"
    priority_name: "priority"
